### ISSUE TITLE
No documentation for certain parameters, no simple_profile or simple_naming parameters

### ISSUE THREAD

**Issue by emmalogo** [LewisLabUCSD/GlyCompare#12]
https://github.com/LewisLabUCSD/GlyCompare/blob/f96e451377534acf1cb5a305450a5704d0a6a0e0/glycompare/pipeline_functions.py#L308

unique_glycan_identifier_to_structure_id=False --> maybe new simple_profile????
 already_glytoucan_id=False --> maybe new simple_naming parameters????

**Comment by bkellman** [comment]
These appear to be new parameters relating to the source_data files
```
1.2. (optional) external_profile_naming.json. Glycompare defaults to index names for each sample (e.g. 1,2,3). If you want to specify a name for each sample use. i.e. paper_epo/source_data/external_profile_naming.json

1.3. (optional) glycan_identifier_to_glytoucan_id.json. If the glycan identifiers in abundance_table.xls are glytoucan_id or m/z which map uniquely (1:1) to glytoucan IDs, this file can be ignored. If m/z can map to multiple isoforms, this file must be completed to specify which m/z correspond to which structures paper_epo/source_data/glycan_identifier_to_glytoucan_id.json

1.4. (optinal) source_data/glycoct/. If part of glycan structures are manually curated, we need a source_data/glycoct/ directory to store all of them (i.e. paper_epo/source_data/glycoct)
```

unique_glycan_identifier_to_structure_id=False --> maybe a boolean indicating if `glycan_identifier_to_glytoucan_id.json` is present
already_glytoucan_id=False --> boolean, if true, glycans in the abundance table are specified by glytoucan id, if false, glycans in the abundance table must be read in separately

@bobaoai, please confirm

**Comment by bobaoai** [comment]
unique_glycan_identifier_to_structure_id=False --> maybe a boolean indicating if glycan_identifier_to_glytoucan_id.json is present

glycan_identifier_to_glytoucan_id.json is requried if unique_glycan_identifier_to_structure_id*already_glytoucan_id=0

unique_glycan_identifier_to_structure_id=True & already_glytoucan_id=True. The GlyTouCan IDs already exist in abundance_table. We don't need glycan_identifier_to_glytoucan_id.json
Example:
https://github.com/LewisLabUCSD/GlyCompare/tree/master/example_data/test_iscience/source_data
unique_glycan_identifier_to_structure_id=True & already_glytoucan_id=False. glycan_identifier_to_glytoucan_id.json is required.
Example: https://github.com/LewisLabUCSD/GlyCompare/blob/master/example_data/paper_hmo/source_data/glycan_identifier_to_structure_id.json

unique_glycan_identifier_to_structure_id=False & already_glytoucan_id=False. glycan_identifier_to_glytoucan_id.json is required.
Example: https://github.com/LewisLabUCSD/GlyCompare/blob/master/example_data/paper_epo/source_data/glycan_identifier_to_structure_id.json

(correct)already_glytoucan_id=False --> boolean, if true, glycans in the abundance table are specified by glytoucan id, if false, glycans in the abundance table must be read in separately
