### ISSUE TITLE
Best Practices: Implicit saving within a function

### ISSUE THREAD

**Issue by bkellman** [LewisLabUCSD/GlyCompare#3]
Best practices (as far as I understand) say we should not save data to files from within a function by default. Can we make this an optional functionality?

**Comment by bobaoai** [comment]
Seriously,,,, I don't know which function are you talking about........ pipeline = input + function +ouput, please please check the code first.

Save the important intermediate file is for **pipeline** not for individual function. I think you are confused with the **pipeline** and **each individual function**. 

Generally, I think the **software** and **pipeline** will force to save the important intermediate file. :)

If you insist, please tell me saving which file you think will "adding lots of reading/write events increases runtime substantially." like 1 or 2 sec?
