### ISSUE TITLE
More efficient version with implicit look up 

### ISSUE THREAD

**Issue by bkellman** [LewisLabUCSD/GlyCompare#4]
https://github.com/bkellman/GlyCompare/blob/5682dad4df50b660c01fc141f16a9bd713116d15/src/customize_motif_vec.py#L130

I'd like to suggest an alternative to this function which sets the keys of a dictionary to the glycoct strings. This avoids the costly subtree function and I think speeds things up a lot. What do you think bokan?
```
def merge_motif_dict_pipe2(glycan_motif_dic):
	# param glyca_motif_dic, glycan motif dictionary output from extract_motif.get_motif_pip
	dic_out = {}
	# iterate over glycans
	for gk in glycan_motif_dic:
		# iterate over glycans of size i
		for m_size in glycan_motif_dic[gk]:
			for m_ij in glycan_motif_dic[gk][m_size]:
				m = str(m_ij)
				if m in dic_out.keys():
					dic_out[m].append(gk)
				else:
					dic_out[m] = [gk]
	return dic_out
```

**Comment by bobaoai** [comment]
I mean if you do search with string(glycoct string) some glycans might have the same topology but the different string. 

Obtain the composition first is a good idea.

**Comment by bkellman** [comment]
I agree, I don't think this would work with glcoct, though it may work with something like linearcode which seems more deterministic.

I don't know anything about graph/topology hashing either, but it could be fun to look into.

I'll add a card to the version 2 "ideas" column on the [project page:](https://github.com/LewisLabUCSD/GlyCompare/projects/1).

I think we can call this a future consideration and close this issue.
