### ISSUE TITLE
Best Practices: the __init__ file specifies global variables which are generally not recommended

### ISSUE THREAD

**Issue by bkellman** [LewisLabUCSD/GlyCompare#6]
For example, if someone wanted to run an analysis to compare linked with unlinked analysis results, they would need to spin up two separate sessions. Additionally, they won't necessarily know that the __init__ file exists.

I think that these may be behaving like global variables which are not recommended for a package ([see #12 & #18](https://opensource.com/article/17/5/30-best-practices-software-development-and-testing))

**Comment by bobaoai** [comment]
Please tell me how to compare linked with unlinked analysis results. 

As there is only one global variable left which is exact_Ture.....
