### ISSUE TITLE
No documentation for certain parameters, no epitope parameter

### ISSUE THREAD

**Issue by emmalogo** [LewisLabUCSD/GlyCompare#9]
https://github.com/LewisLabUCSD/GlyCompare/blob/f96e451377534acf1cb5a305450a5704d0a6a0e0/glycompare/pipeline_functions.py#L395

only_substructures_start_from_root --> boolean value whether to start from core 
core='' --> string representation of the root 
drop_parellel=False --> used in selectmotif.NodeState.nodes_dropping_pipe() , think is used to check if you can drop parallel node edges??? 
drop_diff_abund=True --> used in selectmotif.NodeState.nodes_dropping_pipe(), think is used in to see if you need to generate edges???? 
select_col=[] --> columns passed into the substructure_abd_table for getting substructure weight
remove_core=True --> remove core from the nodes???

**Comment by bkellman** [comment]
only_substructures_start_from_root --> boolean, if true, all substructures will include the root/core substructure. If false, all substructures will be considered.

core='' --> glycoct string describing the root substructure

select_col=[] --> columns passed into the substructure_abd_table for getting substructure weight
remove_core=True --> boolean, if true, the motif set will exclude the provided core, if false, the core will be included

--------------------------------

drop_parellel=False --> used in selectmotif.NodeState.nodes_dropping_pipe() , think is used to check if you can drop parallel node edges???

drop_diff_abund=True --> used in selectmotif.NodeState.nodes_dropping_pipe(), think is used in to see if you need to generate edges???? 

@bobaoai, Can you clarify the meaning of drop_parallel and drop_diff_abund
